import { css, cx } from '@cerberus/styled-system/css';

import type { JSX } from "react";

type Props = {
  /** A className string generated by Cerberus functions. */
  className?: string;
};

/**
 * An `<hr>` element with default and extensible styles.
 *
 * @returns {JSX.Element}
 *
 * @example
 * <SectionDivider />
 */
export const SectionDivider = ({ className }: Props): JSX.Element => {
  const defaultStyles = css({
    color: 'var(--cerberus-neutral-100)',
    mb: '2',
    w: '1312px'
  });

  return <hr role="separator" className={cx(defaultStyles, className)} />;
};
